version: '3'

# Services
services:
  # qBittorrent
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${DOMAINE}`)"
      - "traefik.http.routers.qbittorrent.entrypoints=web, websecure"
      - "traefik.http.routers.qbittorrent.service=qbittorrent"
      - "traefik.http.services.qbittorrent.loadbalancer.passhostheader=true"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - ${DIR_CONFIG_QBITTORRENT}:/config
      - ${DIR_DOWNLOAD}:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
  # Deluge
  # deluge:
  #   container_name: deluge
  #   image: linuxserver/deluge
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.deluge.rule=Host(`deluge.${DOMAINE}`)"
  #     - "traefik.http.routers.deluge.entrypoints=web, websecure"
  #     - "traefik.http.routers.deluge.service=deluge"
  #     - "traefik.http.services.deluge.loadbalancer.passhostheader=true"
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #     - UMASK_SET=022 #optional
  #     - DELUGE_LOGLEVEL=error #optional
  #   restart: unless-stopped
  #   volumes:
  #     - ${DIR_CONFIG_DELUGE}:/config
  #     - ${DIR_DOWNLOAD}:/downloads
  
  # Emby
  emby:
    container_name: emby
    image: linuxserver/emby
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emby.rule=Host(`emby.${DOMAINE}`)"
      - "traefik.http.routers.emby.entrypoints=web, websecure"
      - "traefik.http.routers.emby.service=emby"
      - "traefik.http.services.emby.loadbalancer.passhostheader=true"
    ports:
      - 8096:8096
      - 8920:8920 #optional https
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    restart: unless-stopped
    volumes:
      - ${DIR_CONFIG_EMBY}:/config
      - ${DIR_SERIES}:/data/series
      - ${DIR_MOVIES}:/data/movies
      - ${DIR_GAMES}:/data/games
      - ${DIR_OTHER}:/data/other
      - ${DIR_TRANSCODE}:/transcode #optional

# Network
networks:
  default:
    external:
      name: nas_stack