version: '3'

# Services
services:

  # PHP FPM
  php-fpm:
  # user: uid:gui # For linux users, uncomment this line and replace uid:gui by the numerical values displayed with the command "id" in the terminal, example -> user: 1000:1000
    container_name: web.php-fpm
    image: myprod/php:7.4-dev
    volumes:
      - .:/var/www

  # Nginx
  nginx:
      container_name: web.nginx
      image: nginx:1.18
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.web.rule=Host(`web.nas-stack.nas`)"
        - "traefik.http.routers.web.entrypoints=web, websecure"
        - "traefik.http.routers.web.service=web"
        - "traefik.http.services.web.loadbalancer.passhostheader=true"
      ports:
        - "80"
      volumes:
        - ./docker/nginx/:/etc/nginx/conf.d/
        - ./web:/var/www/web

# Network
networks:
  default:
    external:
      name: nas_stack